# Site settings
title: Test SEB
email: seb@ecedi.fr
name: "Name landing page SEB"
description: "Demonstration d'une landing page sous jekyll."
baseurl: ""
url: "http://belaube.github.io/landing/"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5

#gems: [jekyll-assets]

exclude:
  - .bowerrc
  - bower.json
  - Gruntfile.js
