# Site settings
title: Test SEB
email: seb@ecedi.fr
description: "Demonstration d'une landing page sous jekyll."
baseurl: ""
url: "http://belaube.github.io/landing/"

# Build settings
#markdown: kramdown
#permalink: pretty

exclude:
  - .bowerrc
  - bower.json
  - Gruntfile.js
